### ISSUE TITLE
gss_smの入手方法を教えてください。

### ISSUE THREAD

**Issue by KiyohikoN** [uribo/kspub-dataviz#15]
ご担当者様

中外製薬の中井と申します。
御社の「データ分析のためのデータ可視化入門」を購入しました。
4.4章（page132）に出てくるgss_smの入手方法を教えてください。
よろしくお願いします。

中井清彦
nakaikyh@chugai-pharm.co.jp

**Comment by siero5335** [comment]
ありがとうございます。
gss_smデータですが、socvizパッケージを読み込むことで利用できるようになると思います。
https://cran.r-project.org/web/packages/socviz/index.html

このパッケージは原著者が管理しているパッケージで、
本で使われているいくつかのデータや一部の関数などは、
このパッケージを読み込むことで利用可能になるものがあります。

これで解決しましたら幸いです。
