### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by KiyohikoN** [uribo/kspub-dataviz#16]
3刷を使っています。page275の中盤のgeom_smoth()は正しくはgeom_smooth()だと思います。

**Comment by uribo** [comment]
@KiyohikoN ご報告ありがとうございます。
https://github.com/uribo/kspub-dataviz/commit/d5f4b60991d46fc8b6ee4967b757735b68fd5bc2 にて記載しました。次の版での修正を行わせていただきます。お手数おかけし、申し訳ありませんでした。
