### ISSUE TITLE
plot_section関数について

### ISSUE THREAD

**Issue by KiyohikoN** [uribo/kspub-dataviz#17]
## ページ番号・該当箇所
p.338

## 内容

plot_section関数を作成し、Rationalityでplotを作成しようとすると、以下のエラーメッセージが出ます。対処法を教えてください。

plot_section <- function(section = "Culture", x = "Year",
                        y = "Members", data = asasec,
                        smooth = FALSE){
    require(ggplot2)
    require(splines)
    p <- ggplot(subset(data, Sname == section),
               mapping = aes(x = {{x}}, y = {{y}}))
    
    if(smooth == TRUE) {
        p0 <- p + geom_smooth(color = "#999999",
                             size = 1.2, method = "lm",
                             formula = y ~ ns(x, 3)) +
        scale_x_continuous(breaks = c(seq(2005, 2015, 4))) +
        labs(title = section)
    } else {
        p0 <- p + geom_line(color = "#E69F00", size = 1.2) +
        scale_x_continuous(breaks = c(seq(2005, 2015, 4))) +
        labs(title = section)
    }
    
    print(p0)
    
}

plot_section("Rationality")

＜エラーメッセージ＞
Error: Discrete value supplied to continuous scale
Traceback:

1. plot_section("Rationality")
2. print(p0)   # at line 21 of file <text>
3. print(p0)
4. print.ggplot(p0)
5. ggplot_build(x)
6. ggplot_build.ggplot(x)
7. layout$train_position(data, scale_x(), scale_y())
8. f(..., self = self)
9. self$facet$train_scales(self$panel_scales_x, self$panel_scales_y, 
 .     layout, data, self$facet_params)
10. f(...)
11. scale_apply(layer_data, x_vars, "train", SCALE_X, x_scales)
12. lapply(vars, function(var) {
  .     pieces <- lapply(seq_along(scales), function(i) {
  .         scales[[i]][[method]](data[[var]][scale_index[[i]]])
  .     })
  .     o <- order(unlist(scale_index))[seq_len(sum(lengths(pieces)))]
  .     do.call("c", pieces)[o]
  . })
13. FUN(X[[i]], ...)
14. lapply(seq_along(scales), function(i) {
  .     scales[[i]][[method]](data[[var]][scale_index[[i]]])
  . })
15. FUN(X[[i]], ...)
16. scales[[i]][[method]](data[[var]][scale_index[[i]]])
17. f(..., self = self)
18. self$range$train(x)
19. f(..., self = self)
20. scales::train_continuous(x, self$range)
21. stop("Discrete value supplied to continuous scale", call. = FALSE)

## 利用するR、パッケージの情報

    OS Version : windows10
    R Version : 4.1.3
    ggplot2 Version :3.35

sessioninfo

<details>

```r
sessioninfo::session_info()
```

</details>

**Comment by uribo** [comment]
@KiyohikoN 報告いただき、ありがとうございます。
記載いただいた箇所のコードは下記のように変更いただけますと図が出力されます。

```r
p <- ggplot(subset(data, Sname == section), mapping = aes(x = {{x}}, y = {{y}}))
```

ここを

```r
p <- ggplot(subset(data, Sname == section), mapping = aes_string(x = x, y = y))
```

に変更 (`aes()`関数の代わりに`aes_string()`関数を使います)。

上記は図A.7のコードかと思いますが、同様に図A.8についても`aes_string()`を使った方法に変更いただけますと幸いです。お手数おかけします。

次回の版にて更新内容を反映させていただければと思います。

**Comment by yutannihilation** [comment]
（たまたま見かけたので） aes_string() はdeprecatedになっています。突然消えたりはしないと思うので使っても問題ないですが、今の開発版からはその旨のメッセージが出るようになっています。共有までに。

https://ggplot2.tidyverse.org/dev/reference/aes_.html#life-cycle

**Comment by uribo** [comment]
@yutannihilation 補足いただきありがとうございます。
ggplot2の開発版を導入しても、現時点では `aes(x= x, y= y)`や`aes(x= {{ x }}, y= {{ y }})`では`Error: Discrete value supplied to continuous scale`になるかと思いますが、その理解は正しいでしょうか。

いずれにせよ、`aes_string()`に変更した際はdeprecatedになる旨を追記しておきます。

**Comment by yutannihilation** [comment]
> ggplot2の開発版を導入しても、現時点では `aes(x= x, y= y)`や`aes(x= {{ x }}, y= {{ y }})`では`Error: Discrete value supplied to continuous scale`になる

そうなりますが、それは`x`、`y`に文字列が与えられているからです。`{{ }}` を使うときは、関数のデフォルト値も `"Year"`、`"Members"`（文字列）から `Year`、`Members`（`" "` なしのシンボル）に変更する必要があります。

``` r
library(socviz)

plot_section <- function(section = Culture,
                         x = Year,
                         y = Members, data = asasec,
                         smooth = FALSE, ...) {
  require(ggplot2)
  require(splines)
  # Note use of aes_string() rather than aes()
  p <- ggplot(subset(data, Sname == section),
    mapping = aes(x = {{ x }}, y = {{ y }})
  )

  if (smooth == TRUE) {
    p0 <- p + geom_smooth(
      color = "#999999",
      size = 1.2, ...
    ) +
      scale_x_continuous(breaks = c(seq(2005, 2015, 4))) +
      labs(title = section)
  } else {
    p0 <- p + geom_line(color = "#E69F00", size = 1.2) +
      scale_x_continuous(breaks = c(seq(2005, 2015, 4))) +
      labs(title = section)
  }

  print(p0)
}

plot_section("Rationality")
#> Loading required package: ggplot2
#> Loading required package: splines
```

![](https://i.imgur.com/mvEaQ19.png)

``` r
plot_section("Sexualities", smooth = TRUE)
#> `geom_smooth()` using method = 'loess' and formula = 'y ~ x'
```

![](https://i.imgur.com/pos7lWt.png)

<sup>Created on 2022-05-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by yutannihilation** [comment]
ちなみに`aes_string()`を使わずに文字列で指定したい時はこういう書き方になります。

``` r
plot_section <- function(section = Culture,
                         x = "Year",
                         y = "Members", data = asasec,
                         smooth = FALSE, ...) {

  ...

    mapping = aes(x = .data[[x]], y = .data[[y]])
```

参考： https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html
