### ISSUE TITLE
4.5節のタイトル

### ISSUE THREAD

**Issue by shin5yokoyama** [uribo/kspub-dataviz#2]
4.5節のタイトル，frequency plotsを「度数分布表」と訳していますが，描いているのは「表」ではないので，誤訳と思われます．「回りくどく度数分布表（を可視化する棒グラフ）を描いてみる」と読めないこともないのですが．原著者が，frequency plotとhistogramを使い分けているのも謎です．

3行目を「これは総数や割合の度数分布表に相当します」と訳しているので，もしかしたら訳者はうっかり「度数分布表＝ヒストグラム」としたのかもしれません．

**Comment by siero5335** [comment]
ありがとうございます。確かに表ではなく図ですね。
"度数分布を回りくどく描いてみる" としたいと思います。
