### ISSUE TITLE
第三章のいくつかの図に関して

### ISSUE THREAD

**Issue by mushimaru** [uribo/kspub-dataviz#3]
## ページ番号・箇所

p.109，110，114。

## 正誤

- 誤: 109ページの図3.8と110ページの図3.9，114ページの図3.13に関するコードと本文の記述ではgamが用いられていますが，図では（おそらく）lmが用いられています。

**Comment by kilometer0101** [comment]
ご報告ありがとうございます。
確かに、コード・本文・図の説明ではgeom_smooth()関数の引数がmethod = "gam"となっていますが、図はmethod = "lm"で描かれたものでした。申し訳ありません。
