### ISSUE TITLE
5章

### ISSUE THREAD

**Issue by ricken620** [uribo/kspub-dataviz#5]
些末ではありますが。。
### ページ
p.196　図5.26
### 誤植
凡例タイトルなどが変更前である図5.25と同じままで、コードの結果と異なっている

**Comment by uribo** [comment]
ありがとうございます。ご指摘の通り、図5.26として掲載しているものは誤りです。申し訳ございません。
正しい図は、コード実行時に出力されるものです。
次回改訂時に図の差し替えを行わせていただきます。

ご報告、ありがとうございました。
