### ISSUE TITLE
マイナーな誤植 p202 図６．１脚注

### ISSUE THREAD

**Issue by nnawata** [uribo/kspub-dataviz#8]
## ページ番号・箇所
p202 図６．１脚注

## 正誤
- 誤:  直線を追加
- 正:  回帰線を追加

- 誤:
- 正:

**Comment by siero5335** [comment]
コメントいただきありがとうございます。
こちらは図が直線だけではないため厳密に、という理解でよろしいでしょうか。

**Comment by siero5335** [comment]
コメントいただきありがとうございます。
こちらは直線に限らないものであるためと理解いたしました。

回帰線は地理用語の回帰線が主な使われ方（北回帰線・南回帰線）であるため、
"回帰直線・回帰曲線"を追加としたいと思います。
